### ISSUE TITLE
Do not call Wire.begin inside the sensor.begin

### ISSUE THREAD

**Issue by dizcza** [lewisxhe/SensorLib#10]
Calling `Wire.begin` inside a sensor initialization is a bad practice and developers should avoid it by all means.

QMI8658.

**Comment by lyusupov** [comment]
@dizcza 
would you mind to try **teaching Adafruit** to write their libraries first ?

https://github.com/adafruit/Adafruit_BME680/blob/master/Adafruit_BME680.cpp#L100-L110

**Comment by dizcza** [comment]
I would if I used their lib. Is it a dependency?

**Comment by dizcza** [comment]
A short question. Does QMI8658 output accelerometer values in m/s^2 and gyroscope in degrees or radians?

**Comment by lewisxhe** [comment]
yes
