### ISSUE TITLE
Always crash on BHI260AP IRQ

### ISSUE THREAD

**Issue by vsimionescu** [lewisxhe/SensorLib#11]
In the commit: https://github.com/lewisxhe/SensorLib/commit/d6f515c86adadb3548f5d46ca97e6e29b98cdbaf an always crash was added by this line from SensorBHI260AP.hpp:

  static void handleISR()
    {
        *(bool *)(__data_available) = true;
    }

as the definition of __data_available is: volatile bool SensorBHI260AP::__data_available;

so a bool is cast to bool *  and than dereferenced.

Fix: change to  __data_available = true;

**Comment by lewisxhe** [comment]
Thank you for reminding me that this change was only done for compilation testing and not for hardware testing.
