### ISSUE TITLE
SensorQMI8658.hpp fails to compile in pure esp-idf projects

### ISSUE THREAD

**Issue by Vinzenz82** [lewisxhe/SensorLib#16]
Hi Coders,

Thanks for that nice lib. I use this lib in a esp-idf VsCode project without any Arduino stuff. 
Unfortunatley the file SensorQMI8658.hpp refers at some line of codes to:

`Serial.println(..)`

without using any ifdef switch like:

```c
#if defined(ARDUINO)
            Serial.printf(...);
#else
            printf(...);
#endif`
```
For example here:
https://github.com/lewisxhe/SensorLib/blob/e3579bc8ec2a2f329c08d1bb3e28ef3ba5b1a205/src/SensorQMI8658.hpp#L1764C13-L1764C19

**Comment by lyusupov** [comment]
https://github.com/lewisxhe/SensorLib/actions/runs/7490953952/job/20391015965

**Comment by lewisxhe** [comment]
I have not tested the actual effect of QMI in ESP-IDF. The problem you mentioned has been removed.

**Comment by Vinzenz82** [comment]
Thanks. It's working.
